name: Build Geode Mod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build clang python3 python3-pip

      - name: Clone Geode SDK
        run: |
          git clone https://github.com/geode-sdk/geode.git

      - name: Setup Geode
        run: |
          cd geode
          python3 setup.py install

      - name: Configure
        run: |
          cmake -B build -G Ninja -DGEODE_SDK_PATH=geode

      - name: Build
        run: |
          cmake --build build

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/*.geode
