name: Teste

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rodar minha action
        uses: ./.github/actions/build-geode
        with:
          nome: Michael
