name: Build Geode Mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build clang python3 python3-pip

      - name: Install Geode CLI
        run: |
          pip3 install geode-cli

      - name: Setup Geode
        run: |
          geode sdk install

      - name: Configure
        run: |
          cmake -B build -G Ninja

      - name: Build
        run: |
          cmake --build build

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/*.geode
